
package com.webservice.jdk.wsimport.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "HelloServicePortType", targetNamespace = "http://ws.apache.org/axis2")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloServicePortType {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:sayHello")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://ws.apache.org/axis2", className = "com.webservice.jdk.wsimport.client.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://ws.apache.org/axis2", className = "com.webservice.jdk.wsimport.client.SayHelloResponse")
    public String sayHello();

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:sayHelloToPersion")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHelloToPersion", targetNamespace = "http://ws.apache.org/axis2", className = "com.webservice.jdk.wsimport.client.SayHelloToPersion")
    @ResponseWrapper(localName = "sayHelloToPersionResponse", targetNamespace = "http://ws.apache.org/axis2", className = "com.webservice.jdk.wsimport.client.SayHelloToPersionResponse")
    public String sayHelloToPersion(
        @WebParam(name = "name", targetNamespace = "")
        String name);

}
