
package com.webservice.jdk.wsimport.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "HelloService", targetNamespace = "http://ws.apache.org/axis2", wsdlLocation = "http://localhost:8080/axis2/services/HelloService?wsdl")
public class HelloService
    extends Service
{

    private final static URL HELLOSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/axis2/services/HelloService?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        HELLOSERVICE_WSDL_LOCATION = url;
    }

    public HelloService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloService() {
        super(HELLOSERVICE_WSDL_LOCATION, new QName("http://ws.apache.org/axis2", "HelloService"));
    }

    /**
     * 
     * @return
     *     returns HelloServicePortType
     */
    @WebEndpoint(name = "HelloServiceHttpSoap11Endpoint")
    public HelloServicePortType getHelloServiceHttpSoap11Endpoint() {
        return (HelloServicePortType)super.getPort(new QName("http://ws.apache.org/axis2", "HelloServiceHttpSoap11Endpoint"), HelloServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloServicePortType
     */
    @WebEndpoint(name = "HelloServiceHttpSoap11Endpoint")
    public HelloServicePortType getHelloServiceHttpSoap11Endpoint(WebServiceFeature... features) {
        return (HelloServicePortType)super.getPort(new QName("http://ws.apache.org/axis2", "HelloServiceHttpSoap11Endpoint"), HelloServicePortType.class, features);
    }

}
